name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: innersaavn-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Provision a specific Gradle version so we can run 'gradle wrapper' if needed.
      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      # Optional: basic sanity to ensure build scripts exist and are not empty.
      - name: Check Gradle build scripts
        shell: bash
        run: |
          for f in settings.gradle.kts build.gradle.kts; do
            if [ ! -s "$f" ]; then
              echo "ERROR: $f is missing or empty. Add valid Gradle config before building."; exit 1
            fi
          done

      # If the wrapper is missing, generate it using the provisioned Gradle and then use it for the build.
      - name: Bootstrap Gradle Wrapper if missing
        shell: bash
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle Wrapper not found. Generating with Gradle 8.9..."
            gradle wrapper --gradle-version 8.9 --distribution-type bin
          fi
          chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --stacktrace --no-daemon
