name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: innersaavn-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Ensure Gradle Wrapper is present and executable
        shell: bash
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle Wrapper (./gradlew) not found. Generate it locally with: gradle wrapper --gradle-version 8.9"; exit 1
          fi
          chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --stacktrace --no-daemon
