name: Android Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: Test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      # Set working directory to where gradlew lives (change ./Kreate if needed)
      - name: Show files
        run: ls -la
        working-directory: .  # adjust if monorepo
      - name: Show wrapper files
        run: ls -la gradle/wrapper || true
        working-directory: .  # adjust if monorepo

      - name: Make wrapper executable (if needed)
        run: chmod +x ./gradlew
        working-directory: .  # adjust if monorepo

      - name: Run unit tests
        env:
          JIOSAAVN_TEST_URL: ${{ vars.JIOSAAVN_TEST_URL }}
        run: ./gradlew :composeApp:testGithubReleaseUnitTest --stacktrace
        working-directory: .  # adjust if monorepo
