name: Android Unit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: Test
    defaults:
      run:
        # CHANGE this path to the folder where gradlew lives
        working-directory: .  # e.g., ./Kreate if monorepo

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - name: Locate gradlew
        run: |
          pwd
          ls -la
          find . -maxdepth 4 -name "gradlew" -print
        working-directory: .

      - name: Make wrapper executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        env:
          JIOSAAVN_TEST_URL: ${{ vars.JIOSAAVN_TEST_URL }}
        run: ./gradlew :composeApp:testGithubReleaseUnitTest --stacktrace
