name: Android Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # Use the environment named "Test" so its variables/secrets are available
    environment:
      name: Test

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # Run JVM unit tests for composeApp, passing the environment variable from the "Test" environment.
      # If you stored it as an Environment Variable use vars.JIOSAAVN_TEST_URL; if stored as an Environment Secret use secrets.JIOSAAVN_TEST_URL.
      - name: Run unit tests
        env:
          JIOSAAVN_TEST_URL: ${{ vars.JIOSAAVN_TEST_URL }}
        run: ./gradlew :composeApp:testGithubReleaseUnitTest --stacktrace

      # Upload test reports for inspection (JUnit XML and HTML)
      - name: Upload JUnit XML results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: |
            composeApp/build/test-results/testGithubReleaseUnitTest

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: |
            composeApp/build/reports/tests/testGithubReleaseUnitTest
