name: Android Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: Test

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Locate Gradle Wrapper
        id: locate_wrapper
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          WRAP_PATH="$(find . -maxdepth 4 -type f -name 'gradlew' | head -n1)"
          if [ -z "$WRAP_PATH" ]; then
            echo "::error::Gradle Wrapper not found. Commit gradlew and gradle/wrapper/* at project root."
            exit 1
          fi
          echo "Found wrapper at: $WRAP_PATH"
          WRAP_DIR="$(dirname "$WRAP_PATH")"
          echo "GWRAP_DIR=$WRAP_DIR" >> "$GITHUB_ENV"

      - name: Make wrapper executable
        run: chmod +x ./gradlew
        working-directory: ${{ env.GWRAP_DIR }}

      - name: Show Gradle projects
        run: ./gradlew -q projects || true
        working-directory: ${{ env.GWRAP_DIR }}

      - name: Run unit tests
        env:
          JIOSAAVN_TEST_URL: ${{ vars.JIOSAAVN_TEST_URL }}
        shell: bash
        run: |
          set -e
          if ./gradlew -q help --task testDebugUnitTest >/dev/null 2>&1; then
            TASK="testDebugUnitTest"
          elif ./gradlew -q help --task testReleaseUnitTest >/dev/null 2>&1; then
            TASK="testReleaseUnitTest"
          else
            TASK="test"
          fi
          echo "Running task: $TASK"
          ./gradlew "$TASK" --stacktrace
        working-directory: ${{ env.GWRAP_DIR }}

      - name: Upload JUnit XML results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: |
            **/build/test-results/**

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: |
            **/build/reports/tests/**
